#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/start.h"
#include "images/play.h"
#include "images/lose.h"
#include "images/win.h"
#include "images/player.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
//#include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  DRAW_TITLE,
  PLAY,
  PLAY_STRING,
  WIN,
  WIN_TEXT,
  LOSE,
  LOSE_TEXT
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START; 

  struct SpongePlayer p1 = {100, 20, player};
  
  
  int time = 910;
  char str[40] = " ";

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
        waitForVBlank();
        // Resetting positions
        p1.row = 100;
        p1.col = 20;

        time = 910;

        int jellyRow = randint(30, 140);
        int jellyCol = randint(190, 225);
        
        drawFullScreenImageDMA(start);
        
        state = DRAW_TITLE;
        break;
      case DRAW_TITLE:
        drawString(15, 20, "Press ENTER to play!", RED);

        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = PLAY;
        } // if
        break;
      case PLAY:
        waitForVBlank();
        drawFullScreenImageDMA(play);
        
        
        state = PLAY_STRING;
        break;
      case PLAY_STRING:
        
        
        sprintf(str, "COUNTDOWN: %d", time / 30);
        drawRectDMA(5, 5, 90, 20, BLUE);
        drawString(10, 10, str, RED);
        
        drawRectDMA(jellyRow,  jellyCol, 15, 15, MAGENTA);
        // Sea urchins
        drawRectDMA(120, 120, 25, 25, BLACK);
        drawRectDMA(75, 60, 25, 25, BLACK);
        drawRectDMA(30, 100, 25, 25, BLACK);
        drawRectDMA(50, 150, 25, 25, BLACK);
        
        time--;

        drawImageDMA(p1.row, p1.col, 15, 15, p1.image);
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (p1.col >= 10) {
            undrawImageDMA(p1.row, p1.col, 15, 15, play);
            p1.col -= 1;
            //drawFullScreenImageDMA(play);
            //drawRectDMA(5, 5, 90, 20, BLUE);
            //drawString(10, 10, str, RED);
            drawImageDMA(p1.row, p1.col, 15, 15, p1.image);
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (p1.col <= 225) {
            undrawImageDMA(p1.row, p1.col, 15, 15, play);
            p1.col += 1;
            //drawFullScreenImageDMA(play);
            //drawRectDMA(5, 5, 90, 20, BLUE);
            //drawString(10, 10, str, RED);
            drawImageDMA(p1.row, p1.col, 15, 15, p1.image);
          }
        }
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (p1.row >= 10) {
            undrawImageDMA(p1.row, p1.col, 15, 15, play);
            p1.row -= 1;
            //drawFullScreenImageDMA(play);
            //drawRectDMA(5, 5, 90, 20, BLUE);
            //drawString(10, 10, str, RED);
            drawImageDMA(p1.row, p1.col, 15, 15, p1.image);
          } // if
        } 
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (p1.row <= 150) {
            undrawImageDMA(p1.row, p1.col, 15, 15, play);
            p1.row += 1;
            //drawFullScreenImageDMA(play);
            //drawRectDMA(5, 5, 90, 20, BLUE);
            //drawString(10, 10, str, RED);
            drawImageDMA(p1.row, p1.col, 15, 15, p1.image);
          }
        }
        
        // WIN CONDITION
        if ((p1.row >= jellyRow-15 && p1.row <= jellyRow+15) && (p1.col >= jellyCol-15 && p1.col <= jellyCol+15)) {
          state = WIN;
        } // if

        // LOSE CONDITION
        if ((p1.row >= 120-15 && p1.row <= 120+20) && (p1.col >= 120-15 && p1.col <= 120+25)) {
          state = LOSE;
        } // if
        if ((p1.row >= 75-15 && p1.row <= 75+20) && (p1.col >= 60-15 && p1.col <= 60+25)) {
          state = LOSE;
        } // if
        if ((p1.row >= 30-15 && p1.row <= 30+20) && (p1.col >= 100-15 && p1.col <= 100+25)) {
          state = LOSE;
        } // if
        if ((p1.row >= 50-15 && p1.row <= 50+20) && (p1.col >= 150-15 && p1.col <= 150+25)) {
          state = LOSE;
        } // if
        if (time <= 45) {
          state = LOSE;
        }

        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        } // if
        
        
        break;
      case WIN:
        waitForVBlank();
        drawFullScreenImageDMA(win);

        state = WIN_TEXT;
        break;
      case WIN_TEXT:
        drawString(20, 80, "Congrats, You Won!", GREEN);
        drawString(40, 30, "Press Backspace to play again!", GREEN);
        
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        } // if
        break;

      case LOSE:
        waitForVBlank();
        drawFullScreenImageDMA(lose);
        state = LOSE_TEXT;
        break;
      case LOSE_TEXT:
        drawString(20, 80, "GAME OVER", RED);
        drawString(40, 30, "Press Backspace to try again!", RED);
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = START;
        } // if
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
